<!--

TRACKING CODE FILE

Place your HTML Javascript tracking code generated by Google Analytics in this file.

Code in this file will be HIDDEN when uses are logged in to the website

This file is located at /application/themes/[YOUR THEME NAME]/includes/TRACKING_CODE.php

-->